export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

export const PLAYER_DATA_REQUESTED  = 'PLAYER_DATA_REQUESTED';
export const PLAYER_DATA_RECEIVED   = 'PLAYER_DATA_RECEIVED';
export const PLAYER_DATA_FAILED     = 'PLAYER_DATA_FAILED';
export const PLAYER_LOGOUT          = 'PLAYER_LOGOUT';